### ISSUE TITLE
Does this still carry the MIT license?

### ISSUE THREAD

**Issue by ferventcoder** [rebus-org/RebusSnoop#1]
This looks like it may have been [spun off](https://github.com/rebus-org/Rebus/commit/64b2a6b222ddef7b096cf49069853f3971bfc578) from the main repository. I'm looking for an explicit license for this particular piece of software. It's mostly due to a review I'm doing for the [Chocolatey package](https://chocolatey.org/packages/Rebus.Snoop/2.0.0) for approval. The review comments are visible while the package is under moderation.

Having a LICENSE file directly in the repo or a mention in the README helps to know the explicit license versus anything being implied by where the files used to be. Let me know it can be added by you folks or if it would be accepted if someone submitted a PR for this repository. Thanks!

**Comment by ferventcoder** [comment]
Having a LICENSE file directly in the repo or a mention in the README helps for knowing the license.

**Comment by ferventcoder** [comment]
Let me know it can be added or if it would be accepted if someone submitted a PR for this repository. :D

**Comment by mookid8000** [comment]
[BAM!!1](https://github.com/rebus-org/RebusSnoop/blob/master/LICENSE.md) (oh, sorry - yes it is MIT-licensed)

**Comment by ferventcoder** [comment]
Thanks!

**Comment by mookid8000** [comment]
No, thank you :+1:
